version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file: .env
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    env_file: .env
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
